"""Add ssh_password to devices

Revision ID: 1ea6b2d5d6d9
Revises: fa263b002ace
Create Date: 2025-12-24 04:28:26.728725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ea6b2d5d6d9'
down_revision: Union[str, None] = 'fa263b002ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('ssh_password', sa.String(), nullable=True))
    op.alter_column('metrics', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('metrics', 'metric_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('metrics', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('metrics_time_idx', table_name='metrics')
    op.create_foreign_key(None, 'metrics', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.create_index('metrics_time_idx', 'metrics', [sa.text('time DESC')], unique=False)
    op.alter_column('metrics', 'unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('metrics', 'metric_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('metrics', 'time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('devices', 'ssh_password')
    # ### end Alembic commands ###
