#!/usr/bin/expect -f
set timeout 30
spawn ssh root@74.208.167.166 "sed -i 's/POSTROUTING -o eth+ -j MASQUERADE/POSTROUTING -o eth+ -j MASQUERADE; iptables -t nat -A POSTROUTING -o %i -j MASQUERADE/g' ~/NetGuard/wireguard-config/wg_confs/wg0.conf"
expect {
  "password:" {
    send "DCaoY6yl\r"
  }
}
expect eof

spawn ssh root@74.208.167.166 "docker restart netguard-wireguard"
expect {
  "password:" {
    send "DCaoY6yl\r"
  }
}
expect eof
