#!/usr/bin/expect -f
set timeout 60
spawn scp /Users/muhammedj/Downloads/netguard/verify_apikey.py root@74.208.167.166:~/NetGuard/verify_apikey.py
expect {
  "password:" {
    send "DCaoY6yl\r"
  }
}
expect eof

spawn ssh root@74.208.167.166 "docker cp ~/NetGuard/verify_apikey.py netguard-backend-1:/app/verify_apikey.py && docker exec netguard-backend-1 python /app/verify_apikey.py"
expect {
  "password:" {
    send "DCaoY6yl\r"
  }
}
expect eof
